'use client';

import { useRef } from 'react';

const Arrow = () => <span aria-hidden="true">↗</span>;
const BOOK = 'https://tidycal.com/cjmayer/15-minute-intro';
const bookProps = { href: BOOK, target: '_blank', rel: 'noopener noreferrer' };
const offers = [
  { n:'01', title:'Launch Something', line:'You have a business. Now it needs to look and operate like one.', items:['Website + positioning','Core brand system','Lead capture + calendar','Sales or pitch deck'], c:'orange', visual:<><div className="mini-browser"><b>MAKE IT REAL.</b><span>Positioning / website / systems</span><i /></div><div className="cursor-tag">LAUNCH →</div></> },
  { n:'02', title:'Build an MVP', line:'An idea is useful. A working version is better.', items:['Product definition','Interface + user flows','Working MVP','AI + integrations'], c:'lime', visual:<><div className="flow-node node-a">SKETCH</div><div className="flow-node node-b">FLOW</div><div className="flow-node node-c">PRODUCT</div><div className="flow-line" /></> },
  { n:'03', title:'Modernize the Business', line:'Your company has grown. Your technology may not have grown with it.', items:['Technology assessment','Workflow redesign','Automation + AI','Connected systems'], c:'blue', visual:<><div className="stack old"><i /><i /><i /><i /></div><div className="stack-arrow">→</div><div className="stack new"><strong>ONE SYSTEM</strong><i /><i /></div></> },
  { n:'04', title:'Create the Assets', line:'Sometimes the product is ready and the story isn’t.', items:['Product demos','Sales presentations','Motion + explainer video','Launch assets'], c:'cream', visual:<><div className="frame frame-a">16:9</div><div className="frame frame-b">DEMO</div><div className="play">▶</div></> },
];
const work = [
  { type:'VENTURE', title:'HarborIQ', tags:'INSURANCE · SAAS · AI', outcome:'Built an AI-native operating platform for independent insurance agencies.', art:'harbor', href:'/work/harboriq', image:'/work/harboriq-dashboard.jpg', alt:'HarborIQ agency command center interface' },
  { type:'CLIENT WORK', title:'Sertler & Associates', tags:'INSURANCE · WEBSITE · SYSTEMS', outcome:'Turned a dated agency website into a multilingual, connected digital front door.', art:'launch', href:'/work/sertler-associates', image:'/work/sertler-website.jpg', alt:'Sertler & Associates website displayed on a laptop' },
  { type:'PRODUCT', title:'Life Fitness Portfolio', tags:'FITNESS · HARDWARE · LEADERSHIP', outcome:'Led connected cardio and workplace wellness portfolios across a $420M global business.', art:'fitness', href:'/work/life-fitness', image:'/work/life-fitness-treadmill-poster.jpg', alt:'Life Fitness treadmill in motion' },
  { type:'ADVISORY', title:'Enterprise AI Advisory', tags:'ENTERPRISE · STRATEGY · AI', outcome:'Reframed a multi-year, seven-figure AI program as a focused MVP that could prove value in weeks.', art:'advisory', href:'/work/enterprise-ai-advisory', image:'/work/ai-working-session.jpg', alt:'Justin leading a collaborative AI strategy working session' },
  { type:'PATENT', title:'From Sketch to IP', tags:'HARDWARE · INDUSTRIAL DESIGN · IP', outcome:'Built an immersive product system that moved ideas through prototypes, patents, manufacturing, and market.', art:'patent', href:'/work/sketch-to-ip', image:'/work/inmovement/dt20-standing-desk.webp', alt:'InMovement desktop sit-to-stand workstation' },
];

export default function Home() {
  const rail = useRef<HTMLDivElement>(null);
  const move = (dir:number) => {
    const el = rail.current;
    if (!el) return;
    const card = el.firstElementChild as HTMLElement | null;
    const gap = parseFloat(getComputedStyle(el).columnGap) || 0;
    const step = card ? card.getBoundingClientRect().width + gap : el.clientWidth;
    el.scrollBy({left:dir*step,behavior:'smooth'});
  };
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="wordmark" href="#top" aria-label="WRKSTREAM home"><span>WRK</span>STREAM</a><div className="nav-links"><a href="#building">Ventures</a><a href="#services">Services</a><a href="#work">Work</a><a href="#about">About</a></div><a className="nav-cta" {...bookProps}>Book an intro call <Arrow /></a></nav>

    <section className="hero shell" id="top"><div className="hero-meta eyebrow"><span>Product + venture studio</span><span>Chicago / working everywhere</span></div><h1>We build <em>businesses.</em></h1><div className="hero-bottom"><h2>Sometimes they’re ours.<br/>Sometimes they’re yours.</h2><div className="hero-intro"><p>Products, technology, and experiences built by people who have spent their careers turning ideas into real things.</p><div className="button-row"><a className="button primary" href="#building">See what we build <span>↓</span></a><a className="button ghost" {...bookProps}>Book a call <Arrow /></a></div></div></div>
      <div className="hero-lab" aria-hidden="true"><div className="lab-grid" aria-hidden="true"/><div className="lab-label eyebrow"><span>WRK / LAB 001</span><span>Live system</span></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="artifact artifact-a"><span>01</span><strong>IDENTIFY</strong><small>Opportunity</small></div><div className="artifact artifact-b"><span>02</span><strong>MAKE</strong><small>Prototype</small></div><div className="artifact artifact-c"><span>03</span><strong>SHIP</strong><small>Real world</small></div><div className="lab-core"><div/><span>IDEA</span></div></div>
    </section>

    <section className="building" id="building"><div className="shell building-block"><div className="section-index eyebrow">01 / What we’re building</div><div className="building-head"><h2><span>We have our own</span><em>skin in the game.</em></h2><p>We don’t just advise companies on how to build products and businesses. We build and operate our own.</p></div></div><div className="shell venture-card"><div className="venture-copy"><div className="status"><i/> OPERATING</div><h3>HarborIQ</h3><p>An AI-native operating platform built for independent insurance agencies.</p><a href="/work/harboriq">Explore the venture <Arrow /></a></div><div className="venture-visual packaging"><img loading="lazy" decoding="async" src="/work/harboriq-packaging.jpg" alt="HarborIQ presented as a boxed software product on a studio desk"/></div></div></section>

    <section className="offers-section" id="services"><div className="shell offer-block"><div className="section-index eyebrow">02 / What are you building?</div><div className="offer-intro"><h2>Let’s make it <em>real.</em></h2><p>You may know exactly what you need. You may just know something needs to change. Either way, we can help turn the idea into something people can see, use, buy, or run their business on.</p></div></div><div className="offer-grid shell">{offers.map(o=><article className={`offer ${o.c}`} key={o.n}><div className="offer-count eyebrow">{o.n} / 04</div><div className="offer-art" aria-hidden="true">{o.visual}</div><h3>{o.title}</h3><p>{o.line}</p><ul>{o.items.map(i=><li key={i}>{i}</li>)}</ul><a href="#contact">Talk about this <Arrow /></a></article>)}</div></section>

    <section className="work-section" id="work"><div className="shell work-head"><div><div className="section-index eyebrow">03 / Selected work</div><h2>Things we’ve<br/><em>made real.</em></h2></div><div className="rail-controls"><button onClick={()=>move(-1)} aria-label="Previous projects">←</button><button onClick={()=>move(1)} aria-label="Next projects">→</button></div></div><div className="work-rail" ref={rail}>{work.map((w,i)=><a className="work-card" href={w.href || '#contact'} key={w.title}><div className={`work-art ${w.art} ${w.image ? 'has-image' : ''}`}>{w.image && <img className="work-real-image" loading="lazy" decoding="async" src={w.image} alt={w.alt}/>}<span className="work-num">0{i+1}</span><div className="artifact-mark">WRK/{w.type.slice(0,3)}</div>{!w.image && <div className="art-object"><i/><i/><i/></div>}</div><div className="work-card-copy"><div className="eyebrow">{w.type}</div><h3>{w.title}</h3><small>{w.tags}</small><p>{w.outcome}</p><span className="view-link">View project <Arrow /></span></div></a>)}</div></section>

    <section className="discipline" id="about"><div className="shell discipline-block"><div className="section-index eyebrow">04 / How things get built</div><div className="discipline-grid"><div className="discipline-copy"><h2>Different products.<br/><em>Same discipline.</em></h2><p>Hardware taught us that every component matters. Software taught us that every system connects to another. Running businesses taught us that neither matters unless somebody wants what you built.</p><p>The medium changes. The work is still about understanding the problem, making smart tradeoffs, and getting the right thing into the real world.</p></div><div className="proof"><div><b>20+</b><span>years building products</span></div><div><b>$400M+</b><span>product portfolio experience</span></div><div><b>01</b><span>venture exit</span></div><div><b>HW → AI</b><span>across physical + digital</span></div></div></div></div><div className="build-tape"><span>UNDERSTAND</span><i>→</i><span>DESIGN</span><i>→</i><span>BUILD</span><i>→</i><span>SHIP</span><i>→</i><span>LEARN</span></div></section>

    <section className="advisory"><div className="shell advisory-block"><div className="section-index eyebrow">05 / Enterprise advisory</div><div className="advisory-title"><p className="kicker">Leading something bigger?</p><h2>Some problems aren’t projects.<br/><em>They’re decisions.</em></h2></div><div className="advisory-grid"><div className="advisory-intro"><p>For established companies and leadership teams, WRKSTREAM provides focused advisory work around product, technology, AI, and innovation.</p><a className="button primary" {...bookProps}>Book a 15-minute intro <Arrow /></a></div><div className="advisory-list">{['Where should AI actually matter?','What should we build, buy, or automate?','Which opportunities are worth pursuing?','How do we turn strategy into execution?'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div><div className="workshop-card"><div className="status"><i/> FOCUSED ENGAGEMENT</div><h3>Executive<br/>working sessions</h3><p>Designed around a real business problem — not generic AI education.</p><small>Half-day from $6K<br/>Full-day from $10K</small></div></div></div></section>

    <section className="small" id="partners"><div className="shell small-block"><div className="section-index eyebrow">06 / How we work</div><div className="small-grid"><h2>Small by design.<br/><em>Strategic by default.</em></h2><div><p>Every engagement is led directly by an experienced operator. When a project needs more capability, we bring in trusted developers, designers, engineers, technologists, and creatives.</p><p>You get the flexibility of a larger team without getting handed off to one.</p></div></div></div><div className="shell partner-card"><div><div className="eyebrow">Build with us / Partner network</div><h3>Good people make<br/>the bench better.</h3></div><p>Independent builder, designer, engineer, creative, technologist, or operator? We’re always interested in meeting people who make the work stronger.</p><a className="button ghost" href="mailto:justin@wrkstream.com?subject=Build%20with%20WRKSTREAM">Join the network <Arrow /></a></div></section>

    <footer id="contact"><div className="footer-grid"/><div className="shell footer-inner"><div className="eyebrow">WRKSTREAM / Available for select projects</div><h2>What are you<br/><em>building?</em></h2><p>If it needs to become real, useful, sellable, or operational — we should probably talk.</p><a className="footer-cta" {...bookProps}>Book a 15-minute intro <Arrow /></a><a className="footer-cta-alt" href="mailto:justin@wrkstream.com?subject=Start%20a%20project">Or email justin@wrkstream.com <Arrow /></a><div className="footer-social"><a href="https://www.linkedin.com/in/cjustinmayer/" target="_blank" rel="noopener noreferrer">Justin Mayer on LinkedIn <Arrow /></a><a href="https://www.linkedin.com/company/wrkstream/" target="_blank" rel="noopener noreferrer">WRKSTREAM on LinkedIn <Arrow /></a></div><div className="footer-bottom"><span><b>WRK</b>STREAM</span><span>Product + venture studio</span><span>© 2026 / Chicago</span></div></div></footer>
  </main>;
}
